<template>
  <section class="flex justify-center mb-20">
    <section class="p-4 max-w-[1440px]">
      <div class="flex justify-center">
        <img src="../assets/LogoBig.png" alt="" class="h-[20vh]" />
      </div>
      <div class="text-left flex flex-col gap-5 lg:max-w-[60vw]">
        <span class="w-max">
          <NuxtLink to="./"><p class="underline">...go back</p></NuxtLink>
        </span>
        <p class="font-bold text-2xl">Privacy Policy</p>
        <p class="font-bold">Last updated: December 18, 2023</p>
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You. We use Your Personal data to provide and improve the
          Service. By using the Service, You agree to the collection and use of
          information in accordance with this Privacy Policy. This Privacy
          Policy has been created with the help of the Free Privacy Policy
          Generator.
        </p>
        <p class="font-bold text-2xl">Interpretation and Definitions</p>
        <p class="font-bold text-xl">Interpretation</p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
        <p class="font-bold text-xl">Definitions</p>
        <p class="italic">For the purposes of this Privacy Policy:</p>
        <ul class="ml-10 flex flex-col gap-2">
          <li>
            <b>Account</b> means a unique account created for You to access our
            Service or parts of our Service.
          </li>
          <li>
            <b>Affiliate</b> means an entity that controls, is controlled by or
            is under common control with a party, where "control" means
            ownership of 50% or more of the shares, equity interest or other
            securities entitled to vote for election of directors or other
            managing authority.
          </li>
          <li>
            <b>Application</b> refers to wopebozin, the software program
            provided by the Company.
          </li>
          <li>
            <b>Company</b> (referred to as either "the Company", "We", "Us" or
            "Our" in this Agreement) refers to Wopebozin LLC, Calabasas Avenue,
            Accra.
          </li>
          <li><b>Country</b> refers to: Ghana</li>
          <li>
            <b>Device</b> means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </li>
          <li>
            <b>Personal Data</b> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li><b>Service</b> refers to the Application.</li>
          <li>
            <b>Service Provider</b> means any natural or legal person who
            processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
          <li>
            <b>Usage Data</b> refers to data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <b>You</b> means the individual accessing or using the Service, or
            the company, or other legal entity on behalf of which such
            individual is accessing or using the Service, as applicable.
          </li>
        </ul>
      </div>
    </section>
  </section>

  <Footer />
</template>

<style scoped></style>
